name: pdfmixtool
base: core18
version: '1.0beta'
license: GPL-3.0+
title: PDF Mix Tool
summary: An application to perform common editing operations on PDF files
description: |
  PDF Mix Tool is a simple and lightweight application that allows you to
  perform common editing operations on PDF files.

  Base operations it can perform are the following:

  - Merge two or more files specifying a page set for each of them
  - Rotate pages
  - Composite more pages onto a single one (N-up)
  - Combinations of all of the above

  Besides, it can also mix files alternating their pages, generate booklets,
  add white pages to a PDF file, delete pages from a PDF file, extract pages
  from a PDF file, edit the PDF document information.

grade: stable
confinement: strict

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  desktop:
  desktop-legacy:
  wayland:
  unity7:
  home:
  removable-media:

  # To allow wayland apps access system theme settings
  gsettings:
  
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

apps:
  pdfmixtool:
    command: $SNAP/usr/bin/pdfmixtool
    command-chain:
      - bin/desktop-launch
      - bin/pdfmixtool-launch
    desktop: usr/share/applications/eu.scarpetta.PDFMixTool.desktop

parts:
  pdfmixtool:
    plugin: cmake
    configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/usr]
    source: https://gitlab.com/scarpetta/pdfmixtool/-/archive/v1.0beta/pdfmixtool-v1.0beta.tar.gz
    source-type: tar
    build-packages:
      - build-essential
      - qtbase5-dev
      - qttools5-dev
    stage-packages:
      - dbus
      - qttranslations5-l10n # common translations
      - qtwayland5
      - qt5-gtk-platformtheme # for theming, font settings, cursor and to use gtk3 file chooser
      - qt5-style-plugins # for mouse cursor theme fix
    after: [qt5, libqpdf]
      
  libqpdf:
    plugin: make
    override-build: |
      ./configure --prefix=/usr --disable-static
      make
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install
    source: https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.3.1/qpdf-10.3.1.tar.gz
    source-type: tar
    build-packages:
      - build-essential
      - pkg-config
      - libjpeg8-dev
      - zlib1g-dev
    stage-packages:
      - libjpeg8
      - zlib1g 
      
  qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      
  launchers: # custom launcher to set QT_QPA_PLATFORMTHEME=gtk3 correctly
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
