name: pdfmixtool
version: '0.3.4'
summary: An application to split, merge, rotate and mix PDF files
description: |
  PDF Mix Tool is a simple and lightweight application that allows you to split, merge, rotate and mix PDF files.
  It is written in C++ and depends only on Qt 5 and PoDoFo.

grade: stable
confinement: strict

apps:
  pdfmixtool:
    command: desktop-launch $SNAP/usr/bin/pdfmixtool
    desktop: usr/share/applications/eu.scarpetta.PDFMixTool.desktop
    plugs:
      - home
      - removable-media
      - desktop
      - x11
      - wayland
      - opengl

parts:
  pdfmixtool:
    plugin: cmake
    configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/usr]
    source: https://gitlab.com/scarpetta/pdfmixtool.git
    source-branch: stable
    build-packages:
      - build-essential
      - qtbase5-dev
      - qttools5-dev-tools
    after: [desktop-qt5, libpodofo]
  libpodofo:
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DPODOFO_BUILD_SHARED=1
      - -DPODOFO_HAVE_JPEG_LIB=1
      - -DPODOFO_HAVE_PNG_LIB=1
      - -DPODOFO_HAVE_TIFF_LIB=1
      - -DPODOFO_BUILD_LIB_ONLY=1
    source: https://datapacket.dl.sourceforge.net/project/podofo/podofo/0.9.6/podofo-0.9.6.tar.gz
    source-type: tar
    build-packages:
      - build-essential
      - pkg-config
      - libssl-dev
      - libfontconfig1-dev
      - libtiff5-dev
      - libidn11-dev
      - libjpeg-turbo8-dev
      - libfreetype6-dev
      - libunistring-dev
    stage-packages:
      - libssl1.0.0
      - libfontconfig1
      - libtiff5
      - libidn11
      - libjpeg-turbo8
      - libfreetype6
      - libunistring0
